/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC_08_Ass2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    @Test public void TransactionTest(){
        Transaction T = new Transaction();
        T.setSuccess(false);
        T.setUserName("Jake");
        T.setfailureReason("Not enough change");
        TransactionStorage Tc = new TransactionStorage();
        Tc.addTransaction(T);
        Transaction A = new Transaction();
        A.setSuccess(false);
        A.setUserName("Sam");
        A.setfailureReason("Not enough change");
        Tc.addTransaction(A);

        assertEquals(1,1);


    }

    @Test
    public void testing() {

        assertEquals(1,1);
    }

    @Test
    public void checkCredentialsTest() {
        User cashier = UserManager.checkCredentials("JeremyCashier", "12345");
        User cashierExpected = new Cashier(2, "JeremyCashier");

        assertEquals(cashier.getUserID(), cashierExpected.getUserID());
        assertEquals(cashier.getUserName(), cashierExpected.getUserName());
        assertEquals(cashier.getRole(), "Cashier");
    }

    @Test
    public void getLatestIDTest(){
        UserManager userManager = new UserManager();
        assertEquals(userManager.getLatestUserID(), 4);
    }

    @Test
    public void usernameAvailableTest(){
        UserManager userManager = new UserManager();
        assertTrue(userManager.isUsernameAvailable("TestName"));
        assertFalse(userManager.isUsernameAvailable("JeremyCashier"));
    }

    @Test
    public void savedCardTest(){
        UserManager userManager = new UserManager();
        assertTrue(userManager.checkIfCustomerHasExistingCard("JeremyCashier"));
    }
}
