 /*
  * This Java source file was generated by the Gradle 'init' task.
  */

 
 package CC_08_Ass2;

 import javafx.application.Application;
 import javafx.stage.Stage;


 public class App extends Application{
     public String getGreeting() {
         return "Hello World!";
     }

     public static void main(String[] args) {
         launch(args);
     }

     @Override
     public void start(Stage primaryStage) throws Exception {
         SystemManager systemManager = new SystemManager();

         AppWindow window = new AppWindow(systemManager);

         primaryStage.setTitle("Vending Machine");
         primaryStage.setScene(window.getScene());
         primaryStage.show();

 //        window.run();
     }
 }
